FROM node:14.10-alpine3.12 as frontend

WORKDIR /home/node/app

COPY --chown=node frontend .

RUN npm install

RUN npm run build

FROM quay.io/keycloak/keycloak:11.0.2

COPY --from=frontend /home/node/app/build/. /opt/jboss/keycloak/themes