version: '3'

services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: micro-auth-prod-app
    volumes:
      - ./keycloak/test-realm-export.json:/tmp/test-realm-export.json
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/test-realm-export.json
      - DB_ADDR=db
      - DB_VENDOR=h2
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - "app.test"

  test:
    build: 
      context: ./tests
      args:
        - UID=1000
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-test
    volumes:
      - ./tests:/home/node/app
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome:88.0.4324.150-chromedriver-88.0.4324.96
    networks:
      - default

networks:
  default:
    driver: bridge